### ISSUE TITLE
Getting Started and the Demo folder

### ISSUE THREAD

**Issue by jdmairs** [paularmstrong/build-tracker#159]
I have postgres running.
I tried to follow Getting Started but cannot get my app to upload a build because it cannot find bt-cli.

I then gave up on Getting Started and switched to Demo folder in your repo.
I cloned your repo.
cd demo
sh build.sh (looks good)
yarn bt-cli upload-build  cannot find bt-cli
sh run.sh. (starts server, but I already have that going based on Getting Started
I hit localhost:3000 and I get your cool GUI.

Cannot figure out how to upload one of my builds or your demo build.

**Comment by paularmstrong** [comment]
Please follow the template provided when you create an issue on GitHub. It includes pieces to fill out that help understand if you're experiencing a bug or doing something wrong. Without code and specific steps to reproduce, there's nothing to do here. Since this issue does not follow the template, I'm going to clone it.

Nowhere in the docs does it say you should use the `demo` folder in this repository. The `demo` folder is for https://build-tracker-demo.herokuapp.com only.
