### ISSUE TITLE
Sometimes the markdown table does not show hash changes when the web UI does

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/build-tracker#178]
# Problem

Sometimes, the _unexpected hash change_ does not show up in the Markdown table, but it does show up in the web UI.

**Steps to Reproduce:**

If one of the delta sizes are zero, but not all, and the filename's hash changes.

**Expected Result**

They are expected to have the same behavior

**Actual Result**

The web UI shows a hash icon, but the markdown table will not

**Comment by OliverJAsh** [comment]
Copying my ideas over from our chat.

In my case, all delta sizes were 0 except for brotli. This hints that the file contents changed, in which case I would expect that does _not_ count as an "_unexpected_ hash change", and therefore I would not expect this warning to appear in the Markdown nor in the GUI/app.

We could then have another (separate) warning for "hash changed due to contents changing, but the contents are 99.999% similar, so there's a chance that your bundler is badly configured, e.g. you haven't [extracted the webpack manifest](https://webpack.js.org/concepts/manifest/#the-problem)". Although, that might not be necessary because those rows will always appear in the Markdown table (after removing rows with no changes), which makes it pretty clear that you've got an issue. Furthermore, there's a chance this warning would have a lot of false positives.

**Comment by paularmstrong** [comment]
🦆(rubber-ducking)

If a `getFilenameHash` function is not provided, we calculate the md5 hash of artifact. I expect that webpack hashing is the same or very similar. If the size of the file changes, but the hash is different, this, to me, would mean that it has unexpectedly changed.

However, if one or both of the _compressed_ sizes have changed, this means that the contents changed significantly enough that the hash change would be expected.

In that case, (pseudo-code): 

```
if (hashChanged && sizeDeltas.stat === 0 && !(Object.keys(sizeDeltas).some(key => sizeDeltas[key] !== 0)) {
  // show hash warning
}
```

**Comment by OliverJAsh** [comment]
> If the size of the file changes, but the hash is different, this, to me, would mean that it has unexpectedly changed.

Do you mean "if the size of the file does not change"? Otherwise all changes would be marked as "hash changed unexpectedly".

**Comment by paularmstrong** [comment]
🤦‍♂ yes, if the size *does not change* (will edit)
