### ISSUE TITLE
Github action for posting artifact diff details to PRs

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/build-tracker#57]
# Problem

This repo doesn't have an example of how to get comparison output into its own PRs

# Solution

Build a Github action to provide as a comment to each PR, maybe even commit?

**Comment by DrSensor** [comment]
Hi, 

It's not related to web dev build artifact but you might be interested seeing [this PR][scdlang#3]. I'm currently experimenting the idea of reporting perf result into PR comment using [git-notes][] and _github action_. The basic idea is from [this article][git-tip-of-week-git-notes] which is about storing custom metadata on each commit using [git-notes][]. Basically, every time the PR is sync via push, it will do macro benchmarks then store&push the perf results via _git-notes_ (you can see the data [here][scdlang perf]). I create the reports by querying the notes then feed it to python script (I'm thinking to replace it with [vega-cli][] later). I also create small package called [fluent-git][] which wrap several git-notes operation. However, that project got stalled because there is no project where I can use [fluent-git][].

Let me know if you have some thought 😉

<details><summary>Additional References</summary>

- [Git Dark Magic](https://gist.github.com/DrSensor/d7d005265009b38f2130adc27eae59be)
- [**Vega** – A Visualization Grammar](https://vega.github.io)
</details>

[fluent-git]: https://github.com/DrSensor/fluent-git
[vega-cli]: https://www.npmjs.com/package/vega-cli
[scdlang perf]: https://github.com/DrSensor/scdlang/tree/refs/notes/commits
[git-tip-of-week-git-notes]: http://alblue.bandlem.com/2011/11/git-tip-of-week-git-notes.html
[scdlang#3]: https://github.com/DrSensor/scdlang/pull/3
[git-notes]: https://git-scm.com/docs/git-notes

**Comment by OliverJAsh** [comment]
A similar action that we might be able to borrow ideas from: https://github.com/preactjs/compressed-size-action
